const COUNTRY = [
  {
    value: "AD",
    label_en: "Andorra",
    label_pl: "Andora",
    phone: "376",
  },
  {
    value: "AE",
    label_en: "United Arab Emirates",
    label_pl: "Zjednoczone Emiraty Arabskie",
    phone: "971",
  },
  {
    value: "AF",
    label_en: "Afghanistan",
    label_pl: "Afganistan",
    phone: "93",
  },
  {
    value: "AG",
    label_en: "Antigua and Barbuda",
    label_pl: "Antigua i Barbuda",
    phone: "1-268",
  },
  {
    value: "AI",
    label_en: "Anguilla",
    label_pl: "Anguilla",
    phone: "1-264",
  },
  {
    value: "AL",
    label_en: "Albania",
    label_pl: "Albania",
    phone: "355",
  },
  {
    value: "AM",
    label_en: "Armenia",
    label_pl: "Armenia",
    phone: "374",
  },
  {
    value: "AO",
    label_en: "Angola",
    label_pl: "Angola",
    phone: "244",
  },
  {
    value: "AQ",
    label_en: "Antarctica",
    label_pl: "Antarktyka",
    phone: "672",
  },
  {
    value: "AR",
    label_en: "Argentina",
    label_pl: "Argentyna",
    phone: "54",
  },
  {
    value: "AS",
    label_en: "American Samoa",
    label_pl: "Samoa Amerykańskie",
    phone: "1-684",
  },
  {
    value: "AT",
    label_en: "Austria",
    label_pl: "Austria",
    phone: "43",
  },
  {
    value: "AU",
    label_en: "Australia",
    label_pl: "Australia",
    phone: "61",
  },
  {
    value: "AW",
    label_en: "Aruba",
    label_pl: "Aruba",
    phone: "297",
  },
  {
    value: "AX",
    label_en: "Alland Islands",
    label_pl: "Wyspy Alandzkie",
    phone: "358",
  },
  {
    value: "AZ",
    label_en: "Azerbaijan",
    label_pl: "Azerbejdżan",
    phone: "994",
  },
  {
    value: "BA",
    label_en: "Bosnia and Herzegovina",
    label_pl: "Bośnia i Hercegowina",
    phone: "387",
  },
  {
    value: "BB",
    label_en: "Barbados",
    label_pl: "Barbados",
    phone: "1-246",
  },
  {
    value: "BD",
    label_en: "Bangladesh",
    label_pl: "Bangladesz",
    phone: "880",
  },
  {
    value: "BE",
    label_en: "Belgium",
    label_pl: "Belgia",
    phone: "32",
  },
  {
    value: "BF",
    label_en: "Burkina Faso",
    label_pl: "Burkina Faso",
    phone: "226",
  },
  {
    value: "BG",
    label_en: "Bulgaria",
    label_pl: "Bułgaria",
    phone: "359",
  },
  {
    value: "BH",
    label_en: "Bahrain",
    label_pl: "Bahrajn",
    phone: "973",
  },
  {
    value: "BI",
    label_en: "Burundi",
    label_pl: "Burundi",
    phone: "257",
  },
  {
    value: "BJ",
    label_en: "Benin",
    label_pl: "Benin",
    phone: "229",
  },
  {
    value: "BL",
    label_en: "Saint Barthelemy",
    label_pl: "Saint Barthelemy",
    phone: "590",
  },
  {
    value: "BM",
    label_en: "Bermuda",
    label_pl: "Bermudy",
    phone: "1-441",
  },
  {
    value: "BN",
    label_en: "Brunei Darussalam",
    label_pl: "Brunei",
    phone: "673",
  },
  {
    value: "BO",
    label_en: "Bolivia",
    label_pl: "Boliwia",
    phone: "591",
  },
  {
    value: "BR",
    label_en: "Brazil",
    label_pl: "Brazylia",
    phone: "55",
  },
  {
    value: "BS",
    label_en: "Bahamas",
    label_pl: "Bahamy",
    phone: "1-242",
  },
  {
    value: "BT",
    label_en: "Bhutan",
    label_pl: "Bhutan",
    phone: "975",
  },
  {
    value: "BV",
    label_en: "Bouvet Island",
    label_pl: "Wyspa Bouveta",
    phone: "47",
  },
  {
    value: "BW",
    label_en: "Botswana",
    label_pl: "Botswana",
    phone: "267",
  },
  {
    value: "BY",
    label_en: "Belarus",
    label_pl: "Białoruś",
    phone: "375",
  },
  {
    value: "BZ",
    label_en: "Belize",
    label_pl: "Belize",
    phone: "501",
  },
  {
    value: "CA",
    label_en: "Canada",
    label_pl: "Kanada",
    phone: "1",
  },
  {
    value: "CC",
    label_en: "Cocos (Keeling) Islands",
    label_pl: "Wyspy Kokosowe",
    phone: "61",
  },
  {
    value: "CD",
    label_en: "Congo, Democratic Republic of the",
    label_pl: "Demokratyczna Republika Konga",
    phone: "243",
  },
  {
    value: "CF",
    label_en: "Central African Republic",
    label_pl: "Republika Środkowoafrykańska",
    phone: "236",
  },
  {
    value: "CG",
    label_en: "Congo, Republic of the",
    label_pl: "Kongo",
    phone: "242",
  },
  {
    value: "CH",
    label_en: "Switzerland",
    label_pl: "Szwajcaria",
    phone: "41",
  },
  {
    value: "CI",
    label_en: "Cote d'Ivoire",
    label_pl: "Wybrzeże Kości Słoniowej",
    phone: "225",
  },
  {
    value: "CK",
    label_en: "Cook Islands",
    label_pl: "Wyspy Cooka",
    phone: "682",
  },
  {
    value: "CL",
    label_en: "Chile",
    label_pl: "Chile",
    phone: "56",
  },
  {
    value: "CM",
    label_en: "Cameroon",
    label_pl: "Kamerun",
    phone: "237",
  },
  {
    value: "CN",
    label_en: "China",
    label_pl: "Chiny",
    phone: "86",
  },
  {
    value: "CO",
    label_en: "Colombia",
    label_pl: "Kolumbia",
    phone: "57",
  },
  {
    value: "CR",
    label_en: "Costa Rica",
    label_pl: "Kostaryka",
    phone: "506",
  },
  {
    value: "CU",
    label_en: "Cuba",
    label_pl: "Kuba",
    phone: "53",
  },
  {
    value: "CV",
    label_en: "Cape Verde",
    label_pl: "Republika Zielonego Przylądka",
    phone: "238",
  },
  {
    value: "CW",
    label_en: "Curacao",
    label_pl: "Curacao",
    phone: "599",
  },
  {
    value: "CX",
    label_en: "Christmas Island",
    label_pl: "Wyspa Bożego Narodzenia",
    phone: "61",
  },
  {
    value: "CY",
    label_en: "Cyprus",
    label_pl: "Cypr",
    phone: "357",
  },
  {
    value: "CZ",
    label_en: "Czech Republic",
    label_pl: "Czechy",
    phone: "420",
  },
  {
    value: "DE",
    label_en: "Germany",
    label_pl: "Niemcy",
    phone: "49",
  },
  {
    value: "DJ",
    label_en: "Djibouti",
    label_pl: "Dżibuti",
    phone: "253",
  },
  {
    value: "DK",
    label_en: "Denmark",
    label_pl: "Dania",
    phone: "45",
  },
  {
    value: "DM",
    label_en: "Dominica",
    label_pl: "Dominika",
    phone: "1-767",
  },
  {
    value: "DO",
    label_en: "Dominican Republic",
    label_pl: "Dominikana",
    phone: "1-809",
  },
  {
    value: "DZ",
    label_en: "Algeria",
    label_pl: "Algeria",
    phone: "213",
  },
  {
    value: "EC",
    label_en: "Ecuador",
    label_pl: "Ekwador",
    phone: "593",
  },
  {
    value: "EE",
    label_en: "Estonia",
    label_pl: "Estonia",
    phone: "372",
  },
  {
    value: "EG",
    label_en: "Egypt",
    label_pl: "Egipt",
    phone: "20",
  },
  {
    value: "EH",
    label_en: "Western Sahara",
    label_pl: "Sahara Zachodnia",
    phone: "212",
  },
  {
    value: "ER",
    label_en: "Eritrea",
    label_pl: "Erytrea",
    phone: "291",
  },
  {
    value: "ES",
    label_en: "Spain",
    label_pl: "Hiszpania",
    phone: "34",
  },
  {
    value: "ET",
    label_en: "Ethiopia",
    label_pl: "Etiopia",
    phone: "251",
  },
  {
    value: "FI",
    label_en: "Finland",
    label_pl: "Finlandia",
    phone: "358",
  },
  {
    value: "FJ",
    label_en: "Fiji",
    label_pl: "Fidżi",
    phone: "679",
  },
  {
    value: "FK",
    label_en: "Falkland Islands (Malvinas)",
    label_pl: "Falklandy",
    phone: "500",
  },
  {
    value: "FM",
    label_en: "Micronesia, Federated States of",
    label_pl: "Mikronezja",
    phone: "691",
  },
  {
    value: "FO",
    label_en: "Faroe Islands",
    label_pl: "Wyspy Owcze",
    phone: "298",
  },
  {
    value: "FR",
    label_en: "France",
    label_pl: "Francja",
    phone: "33",
  },
  {
    value: "GA",
    label_en: "Gabon",
    label_pl: "Gabon",
    phone: "241",
  },
  {
    value: "GB",
    label_en: "United Kingdom",
    label_pl: "Wielka Brytania",
    phone: "44",
  },
  {
    value: "GD",
    label_en: "Grenada",
    label_pl: "Grenada",
    phone: "1-473",
  },
  {
    value: "GE",
    label_en: "Georgia",
    label_pl: "Gruzja",
    phone: "995",
  },
  {
    value: "GF",
    label_en: "French Guiana",
    label_pl: "Gujana Francuska",
    phone: "594",
  },
  {
    value: "GG",
    label_en: "Guernsey",
    label_pl: "Guernsey",
    phone: "44",
  },
  {
    value: "GH",
    label_en: "Ghana",
    label_pl: "Ghana",
    phone: "233",
  },
  {
    value: "GI",
    label_en: "Gibraltar",
    label_pl: "Gibraltar",
    phone: "350",
  },
  {
    value: "GL",
    label_en: "Greenland",
    label_pl: "Grenlandia",
    phone: "299",
  },
  {
    value: "GM",
    label_en: "Gambia",
    label_pl: "Gambia",
    phone: "220",
  },
  {
    value: "GN",
    label_en: "Guinea",
    label_pl: "Gwinea",
    phone: "224",
  },
  {
    value: "GP",
    label_en: "Guadeloupe",
    label_pl: "Gwadelupa",
    phone: "590",
  },
  {
    value: "GQ",
    label_en: "Equatorial Guinea",
    label_pl: "Gwinea Równikowa",
    phone: "240",
  },
  {
    value: "GR",
    label_en: "Greece",
    label_pl: "Grecja",
    phone: "30",
  },
  {
    value: "GS",
    label_en: "South Georgia and the South Sandwich Islands",
    label_pl: "Georgia Południowa i Sandwich Południowy",
    phone: "500",
  },
  {
    value: "GT",
    label_en: "Guatemala",
    label_pl: "Gwatemala",
    phone: "502",
  },
  {
    value: "GU",
    label_en: "Guam",
    label_pl: "Guam",
    phone: "1-671",
  },
  {
    value: "GW",
    label_en: "Guinea-Bissau",
    label_pl: "Guinea Bissau",
    phone: "245",
  },
  {
    value: "GY",
    label_en: "Guyana",
    label_pl: "Gujana",
    phone: "592",
  },
  {
    value: "HK",
    label_en: "Hong Kong",
    label_pl: "Hongkong",
    phone: "852",
  },
  {
    value: "HM",
    label_en: "Heard Island and McDonald Islands",
    label_pl: "Wyspy Heard i McDonalda",
    phone: "672",
  },
  {
    value: "HN",
    label_en: "Honduras",
    label_pl: "Honduras",
    phone: "504",
  },
  {
    value: "HR",
    label_en: "Croatia",
    label_pl: "Chorwacja",
    phone: "385",
  },
  {
    value: "HT",
    label_en: "Haiti",
    label_pl: "Haiti",
    phone: "509",
  },
  {
    value: "HU",
    label_en: "Hungary",
    label_pl: "Węgry",
    phone: "36",
  },
  {
    value: "ID",
    label_en: "Indonesia",
    label_pl: "Indonezja",
    phone: "62",
  },
  {
    value: "IE",
    label_en: "Ireland",
    label_pl: "Irlandia",
    phone: "353",
  },
  {
    value: "IL",
    label_en: "Israel",
    label_pl: "Izrael",
    phone: "972",
  },
  {
    value: "IM",
    label_en: "Isle of Man",
    label_pl: "Wyspa Man",
    phone: "44",
  },
  {
    value: "IN",
    label_en: "India",
    label_pl: "Indie",
    phone: "91",
  },
  {
    value: "IO",
    label_en: "British Indian Ocean Territory",
    label_pl: "Brytyjskie Terytorium Oceanu Indyjskiego",
    phone: "246",
  },
  {
    value: "IQ",
    label_en: "Iraq",
    label_pl: "Irak",
    phone: "964",
  },
  {
    value: "IR",
    label_en: "Iran, Islamic Republic of",
    label_pl: "Iran",
    phone: "98",
  },
  {
    value: "IS",
    label_en: "Iceland",
    label_pl: "Islandia",
    phone: "354",
  },
  {
    value: "IT",
    label_en: "Italy",
    label_pl: "Włochy",
    phone: "39",
  },
  {
    value: "JE",
    label_en: "Jersey",
    label_pl: "Jersey",
    phone: "44",
  },
  {
    value: "JM",
    label_en: "Jamaica",
    label_pl: "Jamajka",
    phone: "1-876",
  },
  {
    value: "JO",
    label_en: "Jordan",
    label_pl: "Jordania",
    phone: "962",
  },
  {
    value: "JP",
    label_en: "Japan",
    label_pl: "Japonia",
    phone: "81",
    suggested: true,
  },
  {
    value: "KE",
    label_en: "Kenya",
    label_pl: "Kenia",
    phone: "254",
  },
  {
    value: "KG",
    label_en: "Kyrgyzstan",
    label_pl: "Kirgistan",
    phone: "996",
  },
  {
    value: "KH",
    label_en: "Cambodia",
    label_pl: "Kambodża",
    phone: "855",
  },
  {
    value: "KI",
    label_en: "Kiribati",
    label_pl: "Kiribati",
    phone: "686",
  },
  {
    value: "KM",
    label_en: "Comoros",
    label_pl: "Komory",
    phone: "269",
  },
  {
    value: "KN",
    label_en: "Saint Kitts and Nevis",
    label_pl: "Saint Kitts i Nevis",
    phone: "1-869",
  },
  {
    value: "KP",
    label_en: "Korea, Democratic People's Republic of",
    label_pl: "Korea Północna",
    phone: "850",
  },
  {
    value: "KR",
    label_en: "Korea, Republic of",
    label_pl: "Korea Południowa",
    phone: "82",
  },
  {
    value: "KW",
    label_en: "Kuwait",
    label_pl: "Kuwejt",
    phone: "965",
  },
  {
    value: "KY",
    label_en: "Cayman Islands",
    label_pl: "Kajmany",
    phone: "1-345",
  },
  {
    value: "KZ",
    label_en: "Kazakhstan",
    label_pl: "Kazachstan",
    phone: "7",
  },
  {
    value: "LA",
    label_en: "Lao People's Democratic Republic",
    label_pl: "Laos",
    phone: "856",
  },
  {
    value: "LB",
    label_en: "Lebanon",
    label_pl: "Liban",
    phone: "961",
  },
  {
    value: "LC",
    label_en: "Saint Lucia",
    label_pl: "Saint Lucia",
    phone: "1-758",
  },
  {
    value: "LI",
    label_en: "Liechtenstein",
    label_pl: "Liechtenstein",
    phone: "423",
  },
  {
    value: "LK",
    label_en: "Sri Lanka",
    label_pl: "Sri Lanka",
    phone: "94",
  },
  {
    value: "LR",
    label_en: "Liberia",
    label_pl: "Liberia",
    phone: "231",
  },
  {
    value: "LS",
    label_en: "Lesotho",
    label_pl: "Lesotho",
    phone: "266",
  },
  {
    value: "LT",
    label_en: "Lithuania",
    label_pl: "Litwa",
    phone: "370",
  },
  {
    value: "LU",
    label_en: "Luxembourg",
    label_pl: "Luksemburg",
    phone: "352",
  },
  {
    value: "LV",
    label_en: "Latvia",
    label_pl: "Łotwa",
    phone: "371",
  },
  {
    value: "LY",
    label_en: "Libya",
    label_pl: "Libia",
    phone: "218",
  },
  {
    value: "MA",
    label_en: "Morocco",
    label_pl: "Maroko",
    phone: "212",
  },
  {
    value: "MC",
    label_en: "Monaco",
    label_pl: "Monako",
    phone: "377",
  },
  {
    value: "MD",
    label_en: "Moldova, Republic of",
    label_pl: "Mołdawia",
    phone: "373",
  },
  {
    value: "ME",
    label_en: "Montenegro",
    label_pl: "Czarnogóra",
    phone: "382",
  },
  {
    value: "MF",
    label_en: "Saint Martin (French part)",
    label_pl: "Saint-Martin",
    phone: "590",
  },
  {
    value: "MG",
    label_en: "Madagascar",
    label_pl: "Madagaskar",
    phone: "261",
  },
  {
    value: "MH",
    label_en: "Marshall Islands",
    label_pl: "Wyspy Marshalla",
    phone: "692",
  },
  {
    value: "MK",
    label_en: "Macedonia, the Former Yugoslav Republic of",
    label_pl: "Macedonia",
    phone: "389",
  },
  {
    value: "ML",
    label_en: "Mali",
    label_pl: "Mali",
    phone: "223",
  },
  {
    value: "MM",
    label_en: "Myanmar",
    label_pl: "Mjanma",
    phone: "95",
  },
  {
    value: "MN",
    label_en: "Mongolia",
    label_pl: "Mongolia",
    phone: "976",
  },
  {
    value: "MO",
    label_en: "Macao",
    label_pl: "Makau",
    phone: "853",
  },
  {
    value: "MP",
    label_en: "Northern Mariana Islands",
    label_pl: "Mariany Północne",
    phone: "1-670",
  },
  {
    value: "MQ",
    label_en: "Martinique",
    label_pl: "Martynika",
    phone: "596",
  },
  {
    value: "MR",
    label_en: "Mauritania",
    label_pl: "Mauretania",
    phone: "222",
  },
  {
    value: "MS",
    label_en: "Montserrat",
    label_pl: "Montserrat",
    phone: "1-664",
  },
  {
    value: "MT",
    label_en: "Malta",
    label_pl: "Malta",
    phone: "356",
  },
  {
    value: "MU",
    label_en: "Mauritius",
    label_pl: "Mauritius",
    phone: "230",
  },
  {
    value: "MV",
    label_en: "Maldives",
    label_pl: "Malediwy",
    phone: "960",
  },
  {
    value: "MW",
    label_en: "Malawi",
    label_pl: "Malawi",
    phone: "265",
  },
  {
    value: "MX",
    label_en: "Mexico",
    label_pl: "Meksyk",
    phone: "52",
  },
  {
    value: "MY",
    label_en: "Malaysia",
    label_pl: "Malezja",
    phone: "60",
  },
  {
    value: "MZ",
    label_en: "Mozambique",
    label_pl: "Mozambik",
    phone: "258",
  },
  {
    value: "NA",
    label_en: "Namibia",
    label_pl: "Namibia",
    phone: "264",
  },
  {
    value: "NC",
    label_en: "New Caledonia",
    label_pl: "Nowa Kaledonia",
    phone: "687",
  },
  {
    value: "NE",
    label_en: "Niger",
    label_pl: "Niger",
    phone: "227",
  },
  {
    value: "NF",
    label_en: "Norfolk Island",
    label_pl: "Norfolk",
    phone: "672",
  },
  {
    value: "NG",
    label_en: "Nigeria",
    label_pl: "Nigeria",
    phone: "234",
  },
  {
    value: "NI",
    label_en: "Nicaragua",
    label_pl: "Nikaragua",
    phone: "505",
  },
  {
    value: "NL",
    label_en: "Netherlands",
    label_pl: "Holandia",
    phone: "31",
  },
  {
    value: "NO",
    label_en: "Norway",
    label_pl: "Norwegia",
    phone: "47",
  },
  {
    value: "NP",
    label_en: "Nepal",
    label_pl: "Nepal",
    phone: "977",
  },
  {
    value: "NR",
    label_en: "Nauru",
    label_pl: "Nauru",
    phone: "674",
  },
  {
    value: "NU",
    label_en: "Niue",
    label_pl: "Niue",
    phone: "683",
  },
  {
    value: "NZ",
    label_en: "New Zealand",
    label_pl: "Nowa Zelandia",
    phone: "64",
  },
  {
    value: "OM",
    label_en: "Oman",
    label_pl: "Oman",
    phone: "968",
  },
  {
    value: "PA",
    label_en: "Panama",
    label_pl: "Panama",
    phone: "507",
  },
  {
    value: "PE",
    label_en: "Peru",
    label_pl: "Peru",
    phone: "51",
  },
  {
    value: "PF",
    label_en: "French Polynesia",
    label_pl: "Polinezja Francuska",
    phone: "689",
  },
  {
    value: "PG",
    label_en: "Papua New Guinea",
    label_pl: "Papua-Nowa Gwinea",
    phone: "675",
  },
  {
    value: "PH",
    label_en: "Philippines",
    label_pl: "Filipiny",
    phone: "63",
  },
  {
    value: "PK",
    label_en: "Pakistan",
    label_pl: "Pakistan",
    phone: "92",
  },
  {
    value: "PL",
    label_en: "Poland",
    label_pl: "Polska",
    phone: "48",
  },
  {
    value: "PM",
    label_en: "Saint Pierre and Miquelon",
    label_pl: "Saint-Pierre i Miquelon",
    phone: "508",
  },
  {
    value: "PN",
    label_en: "Pitcairn",
    label_pl: "Pitcairn",
    phone: "870",
  },
  {
    value: "PR",
    label_en: "Puerto Rico",
    label_pl: "Portoryko",
    phone: "1",
  },
  {
    value: "PS",
    label_en: "Palestine, State of",
    label_pl: "Palestyna",
    phone: "970",
  },
  {
    value: "PT",
    label_en: "Portugal",
    label_pl: "Portugalia",
    phone: "351",
  },
  {
    value: "PW",
    label_en: "Palau",
    label_pl: "Palau",
    phone: "680",
  },
  {
    value: "PY",
    label_en: "Paraguay",
    label_pl: "Paragwaj",
    phone: "595",
  },
  {
    value: "QA",
    label_en: "Qatar",
    label_pl: "Katar",
    phone: "974",
  },
  {
    value: "RE",
    label_en: "Reunion",
    label_pl: "Reunion",
    phone: "262",
  },
  {
    value: "RO",
    label_en: "Romania",
    label_pl: "Rumunia",
    phone: "40",
  },
  {
    value: "RS",
    label_en: "Serbia",
    label_pl: "Serbia",
    phone: "381",
  },
  {
    value: "RU",
    label_en: "Russian Federation",
    label_pl: "Rosja",
    phone: "7",
  },
  {
    value: "RW",
    label_en: "Rwanda",
    label_pl: "Rwanda",
    phone: "250",
  },
  {
    value: "SA",
    label_en: "Saudi Arabia",
    label_pl: "Arabia Saudyjska",
    phone: "966",
  },
  {
    value: "SB",
    label_en: "Solomon Islands",
    label_pl: "Wyspy Salomona",
    phone: "677",
  },
  {
    value: "SC",
    label_en: "Seychelles",
    label_pl: "Seszele",
    phone: "248",
  },
  {
    value: "SD",
    label_en: "Sudan",
    label_pl: "Sudan",
    phone: "249",
  },
  {
    value: "SE",
    label_en: "Sweden",
    label_pl: "Szwecja",
    phone: "46",
  },
  {
    value: "SG",
    label_en: "Singapore",
    label_pl: "Singapur",
    phone: "65",
  },
  {
    value: "SH",
    label_en: "Saint Helena",
    label_pl: "Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tri",
    phone: "290",
  },
  {
    value: "SI",
    label_en: "Slovenia",
    label_pl: "Słowenia",
    phone: "386",
  },
  {
    value: "SJ",
    label_en: "Svalbard and Jan Mayen",
    label_pl: "Svalbard i Jan Mayen",
    phone: "47",
  },
  {
    value: "SK",
    label_en: "Slovakia",
    label_pl: "Słowacja",
    phone: "421",
  },
  {
    value: "SL",
    label_en: "Sierra Leone",
    label_pl: "Sierra Leone",
    phone: "232",
  },
  {
    value: "SM",
    label_en: "San Marino",
    label_pl: "San Marino",
    phone: "378",
  },
  {
    value: "SN",
    label_en: "Senegal",
    label_pl: "Senegal",
    phone: "221",
  },
  {
    value: "SO",
    label_en: "Somalia",
    label_pl: "Somalia",
    phone: "252",
  },
  {
    value: "SR",
    label_en: "Suriname",
    label_pl: "Surinam",
    phone: "597",
  },
  {
    value: "SS",
    label_en: "South Sudan",
    label_pl: "Sudan Południowy",
    phone: "211",
  },
  {
    value: "ST",
    label_en: "Sao Tome and Principe",
    label_pl: "Wyspy Świętego Tomasza i Książęca",
    phone: "239",
  },
  {
    value: "SV",
    label_en: "El Salvador",
    label_pl: "Salwador",
    phone: "503",
  },
  {
    value: "SX",
    label_en: "Sint Maarten (Dutch part)",
    label_pl: "Sint Maarten",
    phone: "1-721",
  },
  {
    value: "SY",
    label_en: "Syrian Arab Republic",
    label_pl: "Syria",
    phone: "963",
  },
  {
    value: "SZ",
    label_en: "Swaziland",
    label_pl: "Suazi",
    phone: "268",
  },
  {
    value: "TC",
    label_en: "Turks and Caicos Islands",
    label_pl: "Turks i Caicos",
    phone: "1-649",
  },
  {
    value: "TD",
    label_en: "Chad",
    label_pl: "Czad",
    phone: "235",
  },
  {
    value: "TF",
    label_en: "French Southern Territories",
    label_pl: "Francuskie Terytoria Południowe i Antarktyczne",
    phone: "262",
  },
  {
    value: "TG",
    label_en: "Togo",
    label_pl: "Togo",
    phone: "228",
  },
  {
    value: "TH",
    label_en: "Thailand",
    label_pl: "Tajlandia",
    phone: "66",
  },
  {
    value: "TJ",
    label_en: "Tajikistan",
    label_pl: "Tadżykistan",
    phone: "992",
  },
  {
    value: "TK",
    label_en: "Tokelau",
    label_pl: "Tokelau",
    phone: "690",
  },
  {
    value: "TL",
    label_en: "Timor-Leste",
    label_pl: "Timor Wschodni",
    phone: "670",
  },
  {
    value: "TM",
    label_en: "Turkmenistan",
    label_pl: "Turkmenistan",
    phone: "993",
  },
  {
    value: "TN",
    label_en: "Tunisia",
    label_pl: "Tunezja",
    phone: "216",
  },
  {
    value: "TO",
    label_en: "Tonga",
    label_pl: "Tonga",
    phone: "676",
  },
  {
    value: "TR",
    label_en: "Turkey",
    label_pl: "Turcja",
    phone: "90",
  },
  {
    value: "TT",
    label_en: "Trinidad and Tobago",
    label_pl: "Trinidad i Tobago",
    phone: "1-868",
  },
  {
    value: "TV",
    label_en: "Tuvalu",
    label_pl: "Tuvalu",
    phone: "688",
  },
  {
    value: "TW",
    label_en: "Taiwan, Province of China",
    label_pl: "Tajwan",
    phone: "886",
  },
  {
    value: "TZ",
    label_en: "United Republic of Tanzania",
    label_pl: "Tanzania",
    phone: "255",
  },
  {
    value: "UA",
    label_en: "Ukraine",
    label_pl: "Ukraina",
    phone: "380",
  },
  {
    value: "UG",
    label_en: "Uganda",
    label_pl: "Uganda",
    phone: "256",
  },
  {
    value: "US",
    label_en: "United States",
    label_pl: "Stany Zjednoczone",
    phone: "1",
    suggested: true,
  },
  {
    value: "UY",
    label_en: "Uruguay",
    label_pl: "Urugwaj",
    phone: "598",
  },
  {
    value: "UZ",
    label_en: "Uzbekistan",
    label_pl: "Uzbekistan",
    phone: "998",
  },
  {
    value: "VA",
    label_en: "Holy See (Vatican City State)",
    label_pl: "Watykan",
    phone: "379",
  },
  {
    value: "VC",
    label_en: "Saint Vincent and the Grenadines",
    label_pl: "Saint Vincent i Grenadyny",
    phone: "1-784",
  },
  {
    value: "VE",
    label_en: "Venezuela",
    label_pl: "Wenezuela",
    phone: "58",
  },
  {
    value: "VG",
    label_en: "British Virgin Islands",
    label_pl: "Brytyjskie Wyspy Dziewicze",
    phone: "1-284",
  },
  {
    value: "VI",
    label_en: "US Virgin Islands",
    label_pl: "Wyspy Dziewicze Stanów Zjednoczonych",
    phone: "1-340",
  },
  {
    value: "VN",
    label_en: "Vietnam",
    label_pl: "Wietnam",
    phone: "84",
  },
  {
    value: "VU",
    label_en: "Vanuatu",
    label_pl: "Vanuatu",
    phone: "678",
  },
  {
    value: "WF",
    label_en: "Wallis and Futuna",
    label_pl: "Wallis i Futuna",
    phone: "681",
  },
  {
    value: "WS",
    label_en: "Samoa",
    label_pl: "Samoa",
    phone: "685",
  },
  {
    value: "XK",
    label_en: "Kosovo",
    label_pl: "Kosowo",
    phone: "383",
  },
  {
    value: "YE",
    label_en: "Yemen",
    label_pl: "Jemen",
    phone: "967",
  },
  {
    value: "YT",
    label_en: "Mayotte",
    label_pl: "Majotta",
    phone: "262",
  },
  {
    value: "ZA",
    label_en: "South Africa",
    label_pl: "Republika Południowej Afryki",
    phone: "27",
  },
  {
    value: "ZM",
    label_en: "Zambia",
    label_pl: "Zambia",
    phone: "260",
  },
  {
    value: "ZW",
    label_en: "Zimbabwe",
    label_pl: "Zimbabwe",
    phone: "263",
  },
];

export default COUNTRY;
